import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'edge';

interface ServiceData {
  name: string;
  nameKo?: string;
  description: string;
  descriptionKo?: string;
  homepage: string;
  apiBase: string;
  productPage?: {
    urlPattern?: string;
    sampleUrl?: string;
    dataSource?: 'json-ld' | 'meta' | 'dom' | 'api';
    selectors?: {
      title?: string;
      price?: string;
      currency?: string;
      image?: string;
      description?: string;
      sku?: string;
      brand?: string;
      availability?: string;
      rating?: string;
      reviewCount?: string;
    };
    notes?: string;
  };
  endpoints: {
    id: string;
    path: string;
    method: string;
    description: string;
    auth: boolean;
    params: string;
  }[];
  authType: string;
  rateLimit: string;
  contactEmail: string;
  slug?: string;
}

function generateAiTxt(service: ServiceData, slug: string): string {
  const productPage = service.productPage;
  const hasProductInfo = Boolean(
    productPage?.urlPattern
    || productPage?.sampleUrl
    || productPage?.dataSource
    || productPage?.notes
    || Object.values(productPage?.selectors || {}).some(Boolean)
  );

  return `# =============================================================================
# ${service.name} AI Interaction Specification (ai.txt)
# Generated by Eoynx Agent Gateway
# Hosted at: https://eoynx.com/s/${slug}
# =============================================================================

[System.Context]
Name: ${service.name}
${service.nameKo ? `Name_KO: ${service.nameKo}` : ''}
Description: ${service.description}
${service.descriptionKo ? `Description_KO: ${service.descriptionKo}` : ''}
Homepage: ${service.homepage}
Contact: ${service.contactEmail}

[API.Base]
URL: ${service.apiBase}

[API.Endpoints]
${service.endpoints.map((ep, i) => `
## ${i + 1}. ${ep.description || 'Endpoint'}
Endpoint: ${ep.method} ${service.apiBase}${ep.path}
Auth: ${ep.auth ? 'Required' : 'Not Required'}
${ep.params ? `Parameters: ${ep.params}` : ''}`).join('\n')}

[Authentication.Policy]
Type: ${service.authType === 'none' ? 'None' : service.authType === 'api_key' ? 'API Key' : service.authType === 'jwt' ? 'JWT Bearer Token' : 'OAuth 2.0'}
${service.authType !== 'none' ? `Header: ${service.authType === 'api_key' ? 'X-API-Key' : 'Authorization: Bearer <token>'}` : ''}

[Rate.Limits]
Default: ${service.rateLimit}

${hasProductInfo ? `
[Product.Page]
URL_Pattern: ${productPage?.urlPattern || ''}
Sample_URL: ${productPage?.sampleUrl || ''}
Data_Source: ${productPage?.dataSource || ''}
${productPage?.selectors ? `Selectors:
  Title: ${productPage.selectors.title || ''}
  Price: ${productPage.selectors.price || ''}
  Currency: ${productPage.selectors.currency || ''}
  Image: ${productPage.selectors.image || ''}
  Description: ${productPage.selectors.description || ''}
  SKU: ${productPage.selectors.sku || ''}
  Brand: ${productPage.selectors.brand || ''}
  Availability: ${productPage.selectors.availability || ''}
  Rating: ${productPage.selectors.rating || ''}
  ReviewCount: ${productPage.selectors.reviewCount || ''}
` : ''}
${productPage?.notes ? `Notes: ${productPage.notes}` : ''}
` : ''}

# =============================================================================
# Generated via Eoynx Agent Gateway
# https://eoynx.com
# =============================================================================
`;
}

function generateJsonLd(service: ServiceData, slug: string): object {
  const productPage = service.productPage;
  return {
    '@context': 'https://schema.org',
    '@type': 'WebAPI',
    '@id': `https://eoynx.com/s/${slug}`,
    name: service.name,
    alternateName: service.nameKo || undefined,
    description: service.description,
    url: service.homepage,
    documentation: `${service.homepage}/docs`,
    provider: {
      '@type': 'Organization',
      name: service.name,
      email: service.contactEmail,
    },
    endpointUrl: service.apiBase,
    potentialAction: service.endpoints.map(ep => ({
      '@type': ep.method === 'GET' ? 'ReadAction' : 'Action',
      name: ep.description || ep.path,
      target: {
        '@type': 'EntryPoint',
        urlTemplate: `${service.apiBase}${ep.path}`,
        httpMethod: ep.method,
      },
    })),
    additionalProperty: [
      {
        '@type': 'PropertyValue',
        name: 'authType',
        value: service.authType,
      },
      {
        '@type': 'PropertyValue',
        name: 'rateLimit',
        value: service.rateLimit,
      },
      ...(productPage ? [
        {
          '@type': 'PropertyValue',
          name: 'productPage',
          value: productPage,
        },
      ] : []),
    ],
  };
}

export async function POST(request: NextRequest) {
  try {
    const serviceData: ServiceData = await request.json();

    if (!serviceData.name || !serviceData.apiBase || !serviceData.description) {
      return NextResponse.json(
        { error: 'Missing required fields: name, apiBase, description' },
        { status: 400 }
      );
    }

    const slug = serviceData.slug || 'preview';
    const aiTxt = generateAiTxt(serviceData, slug);
    const jsonLd = generateJsonLd(serviceData, slug);

    return NextResponse.json({
      success: true,
      aiTxt,
      jsonLd,
    });
  } catch (error) {
    console.error('Generate spec error:', error);
    return NextResponse.json(
      { error: 'Failed to generate spec' },
      { status: 500 }
    );
  }
}