'use client';

import { useState } from 'react';
import { DashboardIcon, KeyIcon, ShieldIcon } from '@/components/brand/FeatureIcons';

interface ServiceData {
  name: string;
  nameKo: string;
  description: string;
  descriptionKo: string;
  homepage: string;
  apiBase: string;
  endpoints: EndpointConfig[];
  authType: 'none' | 'api_key' | 'jwt' | 'oauth2';
  rateLimit: string;
  contactEmail: string;
}

interface EndpointConfig {
  id: string;
  path: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  description: string;
  auth: boolean;
  params: string;
}

const defaultEndpoint: EndpointConfig = {
  id: crypto.randomUUID(),
  path: '/api/data',
  method: 'GET',
  description: '',
  auth: false,
  params: '',
};

const initialServiceData: ServiceData = {
  name: '',
  nameKo: '',
  description: '',
  descriptionKo: '',
  homepage: '',
  apiBase: '',
  endpoints: [{ ...defaultEndpoint }],
  authType: 'none',
  rateLimit: '100/min',
  contactEmail: '',
};

export default function ServicesPage() {
  const [serviceData, setServiceData] = useState<ServiceData>(initialServiceData);
  const [previewMode, setPreviewMode] = useState<'ai.txt' | 'llms.txt' | 'json-ld'>('ai.txt');
  const [isSaving, setIsSaving] = useState(false);
  const [savedUrl, setSavedUrl] = useState<string | null>(null);

  const updateField = <K extends keyof ServiceData>(field: K, value: ServiceData[K]) => {
    setServiceData(prev => ({ ...prev, [field]: value }));
  };

  const addEndpoint = () => {
    setServiceData(prev => ({
      ...prev,
      endpoints: [...prev.endpoints, { ...defaultEndpoint, id: crypto.randomUUID() }],
    }));
  };

  const updateEndpoint = (id: string, field: keyof EndpointConfig, value: string | boolean) => {
    setServiceData(prev => ({
      ...prev,
      endpoints: prev.endpoints.map(ep =>
        ep.id === id ? { ...ep, [field]: value } : ep
      ),
    }));
  };

  const removeEndpoint = (id: string) => {
    setServiceData(prev => ({
      ...prev,
      endpoints: prev.endpoints.filter(ep => ep.id !== id),
    }));
  };

  const generatePreview = (): string => {
    const { name, nameKo, description, descriptionKo, homepage, apiBase, endpoints, authType, rateLimit, contactEmail } = serviceData;
    
    if (previewMode === 'ai.txt') {
      return `# =============================================================================
# ${name || 'Your Service'} AI Interaction Specification (ai.txt)
# Generated by Eoynx Agent Gateway
# =============================================================================

[System.Context]
Name: ${name || 'Your Service Name'}
${nameKo ? `Name_KO: ${nameKo}` : ''}
Description: ${description || 'Your service description'}
${descriptionKo ? `Description_KO: ${descriptionKo}` : ''}
Homepage: ${homepage || 'https://your-domain.com'}
Contact: ${contactEmail || 'support@your-domain.com'}

[API.Base]
URL: ${apiBase || 'https://your-domain.com/api'}

[API.Endpoints]
${endpoints.map((ep, i) => `
## ${i + 1}. ${ep.description || 'Endpoint'}
Endpoint: ${ep.method} ${ep.path}
Auth: ${ep.auth ? 'Required' : 'Not Required'}
${ep.params ? `Parameters: ${ep.params}` : ''}`).join('\n')}

[Authentication.Policy]
Type: ${authType === 'none' ? 'None' : authType === 'api_key' ? 'API Key' : authType === 'jwt' ? 'JWT Bearer Token' : 'OAuth 2.0'}
${authType !== 'none' ? `Header: ${authType === 'api_key' ? 'X-API-Key' : 'Authorization: Bearer <token>'}` : ''}

[Rate.Limits]
Default: ${rateLimit}

# Generated via https://eoynx.com
# Powered by Eoynx Agent Gateway`;
    }
    
    if (previewMode === 'llms.txt') {
      return `# ${name || 'Your Service'} - AI Agent Instructions
# Generated by Eoynx

## About
${description || 'Your service description'}

## API Base URL
${apiBase || 'https://your-domain.com/api'}

## Available Endpoints
${endpoints.map(ep => `
### ${ep.method} ${ep.path}
${ep.description || 'No description'}
${ep.auth ? '⚠️ Authentication required' : '✓ No authentication needed'}
${ep.params ? `Parameters: ${ep.params}` : ''}`).join('\n')}

## Authentication
${authType === 'none' ? 'No authentication required.' : 
  authType === 'api_key' ? 'Include X-API-Key header with your API key.' :
  authType === 'jwt' ? 'Include Authorization: Bearer <token> header.' :
  'Use OAuth 2.0 flow for authentication.'}

## Rate Limits
${rateLimit}

## Contact
${contactEmail || 'support@your-domain.com'}

---
Generated via https://eoynx.com`;
    }
    
    // JSON-LD
    return JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'WebAPI',
      name: name || 'Your Service',
      alternateName: nameKo || undefined,
      description: description || 'Your service description',
      url: homepage || 'https://your-domain.com',
      documentation: `${homepage}/docs`,
      provider: {
        '@type': 'Organization',
        name: name,
        email: contactEmail,
      },
      endpointUrl: apiBase,
      availableChannels: endpoints.map(ep => ({
        '@type': 'ServiceChannel',
        name: ep.description || ep.path,
        serviceUrl: `${apiBase}${ep.path}`,
        httpMethod: ep.method,
      })),
    }, null, 2);
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      // TODO: 실제 API 호출로 Supabase에 저장
      const response = await fetch('/api/services', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(serviceData),
      });
      
      if (response.ok) {
        const data = await response.json();
        setSavedUrl(`https://eoynx.com/s/${data.slug}`);
      }
    } catch (error) {
      console.error('Failed to save:', error);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* 페이지 제목 */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-onyx-100 flex items-center gap-2">
            <DashboardIcon className="w-7 h-7 text-dawn-500" />
            서비스 등록
          </h1>
          <p className="mt-1 text-sm text-onyx-400">
            AI 에이전트가 이해할 수 있는 구조화된 데이터를 생성합니다.
          </p>
        </div>
        <div className="text-xs text-onyx-500 bg-onyx-800/50 px-3 py-1 rounded-full">
          Free Tier
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* 입력 폼 */}
        <div className="space-y-6">
          {/* 기본 정보 */}
          <div className="bg-onyx-900/50 border border-onyx-800 rounded-xl p-6">
            <h2 className="text-lg font-semibold text-onyx-100 mb-4 flex items-center gap-2">
              <span className="w-6 h-6 bg-dawn-500/20 text-dawn-400 rounded-full flex items-center justify-center text-sm">1</span>
              기본 정보
            </h2>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-onyx-300 mb-1">서비스명 (영문) *</label>
                  <input
                    type="text"
                    value={serviceData.name}
                    onChange={(e) => updateField('name', e.target.value)}
                    placeholder="My Awesome API"
                    className="w-full bg-onyx-800 border border-onyx-700 rounded-lg px-3 py-2 text-onyx-100 placeholder-onyx-500 focus:border-dawn-500 focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block text-sm text-onyx-300 mb-1">서비스명 (한글)</label>
                  <input
                    type="text"
                    value={serviceData.nameKo}
                    onChange={(e) => updateField('nameKo', e.target.value)}
                    placeholder="나의 멋진 API"
                    className="w-full bg-onyx-800 border border-onyx-700 rounded-lg px-3 py-2 text-onyx-100 placeholder-onyx-500 focus:border-dawn-500 focus:outline-none"
                  />
                </div>
              </div>
              <div>
                <label className="block text-sm text-onyx-300 mb-1">설명 (영문) *</label>
                <textarea
                  value={serviceData.description}
                  onChange={(e) => updateField('description', e.target.value)}
                  placeholder="A comprehensive API for..."
                  rows={2}
                  className="w-full bg-onyx-800 border border-onyx-700 rounded-lg px-3 py-2 text-onyx-100 placeholder-onyx-500 focus:border-dawn-500 focus:outline-none resize-none"
                />
              </div>
              <div>
                <label className="block text-sm text-onyx-300 mb-1">설명 (한글)</label>
                <textarea
                  value={serviceData.descriptionKo}
                  onChange={(e) => updateField('descriptionKo', e.target.value)}
                  placeholder="종합 API 서비스로..."
                  rows={2}
                  className="w-full bg-onyx-800 border border-onyx-700 rounded-lg px-3 py-2 text-onyx-100 placeholder-onyx-500 focus:border-dawn-500 focus:outline-none resize-none"
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-onyx-300 mb-1">홈페이지 URL *</label>
                  <input
                    type="url"
                    value={serviceData.homepage}
                    onChange={(e) => updateField('homepage', e.target.value)}
                    placeholder="https://example.com"
                    className="w-full bg-onyx-800 border border-onyx-700 rounded-lg px-3 py-2 text-onyx-100 placeholder-onyx-500 focus:border-dawn-500 focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block text-sm text-onyx-300 mb-1">API Base URL *</label>
                  <input
                    type="url"
                    value={serviceData.apiBase}
                    onChange={(e) => updateField('apiBase', e.target.value)}
                    placeholder="https://api.example.com"
                    className="w-full bg-onyx-800 border border-onyx-700 rounded-lg px-3 py-2 text-onyx-100 placeholder-onyx-500 focus:border-dawn-500 focus:outline-none"
                  />
                </div>
              </div>
            </div>
          </div>

          {/* API 엔드포인트 */}
          <div className="bg-onyx-900/50 border border-onyx-800 rounded-xl p-6">
            <h2 className="text-lg font-semibold text-onyx-100 mb-4 flex items-center gap-2">
              <span className="w-6 h-6 bg-dawn-500/20 text-dawn-400 rounded-full flex items-center justify-center text-sm">2</span>
              API 엔드포인트
            </h2>
            <div className="space-y-4">
              {serviceData.endpoints.map((endpoint, index) => (
                <div key={endpoint.id} className="bg-onyx-800/50 border border-onyx-700 rounded-lg p-4">
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-sm text-onyx-400">엔드포인트 #{index + 1}</span>
                    {serviceData.endpoints.length > 1 && (
                      <button
                        onClick={() => removeEndpoint(endpoint.id)}
                        className="text-red-400 hover:text-red-300 text-sm"
                      >
                        삭제
                      </button>
                    )}
                  </div>
                  <div className="grid grid-cols-4 gap-3">
                    <div className="col-span-1">
                      <select
                        value={endpoint.method}
                        onChange={(e) => updateEndpoint(endpoint.id, 'method', e.target.value)}
                        className="w-full bg-onyx-700 border border-onyx-600 rounded-lg px-2 py-2 text-onyx-100 focus:border-dawn-500 focus:outline-none text-sm"
                      >
                        <option value="GET">GET</option>
                        <option value="POST">POST</option>
                        <option value="PUT">PUT</option>
                        <option value="DELETE">DELETE</option>
                      </select>
                    </div>
                    <div className="col-span-3">
                      <input
                        type="text"
                        value={endpoint.path}
                        onChange={(e) => updateEndpoint(endpoint.id, 'path', e.target.value)}
                        placeholder="/api/endpoint"
                        className="w-full bg-onyx-700 border border-onyx-600 rounded-lg px-3 py-2 text-onyx-100 placeholder-onyx-500 focus:border-dawn-500 focus:outline-none text-sm font-mono"
                      />
                    </div>
                  </div>
                  <div className="mt-3">
                    <input
                      type="text"
                      value={endpoint.description}
                      onChange={(e) => updateEndpoint(endpoint.id, 'description', e.target.value)}
                      placeholder="이 엔드포인트의 설명..."
                      className="w-full bg-onyx-700 border border-onyx-600 rounded-lg px-3 py-2 text-onyx-100 placeholder-onyx-500 focus:border-dawn-500 focus:outline-none text-sm"
                    />
                  </div>
                  <div className="mt-3 flex items-center gap-4">
                    <label className="flex items-center gap-2 text-sm text-onyx-300">
                      <input
                        type="checkbox"
                        checked={endpoint.auth}
                        onChange={(e) => updateEndpoint(endpoint.id, 'auth', e.target.checked)}
                        className="rounded bg-onyx-700 border-onyx-600 text-dawn-500 focus:ring-dawn-500"
                      />
                      인증 필요
                    </label>
                    <input
                      type="text"
                      value={endpoint.params}
                      onChange={(e) => updateEndpoint(endpoint.id, 'params', e.target.value)}
                      placeholder="파라미터 (예: q, limit, page)"
                      className="flex-1 bg-onyx-700 border border-onyx-600 rounded-lg px-3 py-1.5 text-onyx-100 placeholder-onyx-500 focus:border-dawn-500 focus:outline-none text-sm"
                    />
                  </div>
                </div>
              ))}
              <button
                onClick={addEndpoint}
                className="w-full py-2 border border-dashed border-onyx-600 rounded-lg text-onyx-400 hover:text-onyx-200 hover:border-onyx-500 transition-colors text-sm"
              >
                + 엔드포인트 추가
              </button>
            </div>
          </div>

          {/* 인증 & 설정 */}
          <div className="bg-onyx-900/50 border border-onyx-800 rounded-xl p-6">
            <h2 className="text-lg font-semibold text-onyx-100 mb-4 flex items-center gap-2">
              <span className="w-6 h-6 bg-dawn-500/20 text-dawn-400 rounded-full flex items-center justify-center text-sm">3</span>
              인증 & 설정
            </h2>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-onyx-300 mb-1">인증 방식</label>
                  <select
                    value={serviceData.authType}
                    onChange={(e) => updateField('authType', e.target.value as ServiceData['authType'])}
                    className="w-full bg-onyx-800 border border-onyx-700 rounded-lg px-3 py-2 text-onyx-100 focus:border-dawn-500 focus:outline-none"
                  >
                    <option value="none">인증 없음</option>
                    <option value="api_key">API Key</option>
                    <option value="jwt">JWT Bearer Token</option>
                    <option value="oauth2">OAuth 2.0</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm text-onyx-300 mb-1">Rate Limit</label>
                  <select
                    value={serviceData.rateLimit}
                    onChange={(e) => updateField('rateLimit', e.target.value)}
                    className="w-full bg-onyx-800 border border-onyx-700 rounded-lg px-3 py-2 text-onyx-100 focus:border-dawn-500 focus:outline-none"
                  >
                    <option value="10/min">10 req/min</option>
                    <option value="60/min">60 req/min</option>
                    <option value="100/min">100 req/min</option>
                    <option value="1000/min">1000 req/min</option>
                    <option value="unlimited">Unlimited</option>
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-sm text-onyx-300 mb-1">연락처 이메일</label>
                <input
                  type="email"
                  value={serviceData.contactEmail}
                  onChange={(e) => updateField('contactEmail', e.target.value)}
                  placeholder="api-support@example.com"
                  className="w-full bg-onyx-800 border border-onyx-700 rounded-lg px-3 py-2 text-onyx-100 placeholder-onyx-500 focus:border-dawn-500 focus:outline-none"
                />
              </div>
            </div>
          </div>

          {/* 저장 버튼 */}
          <button
            onClick={handleSave}
            disabled={isSaving || !serviceData.name || !serviceData.apiBase}
            className="w-full py-3 bg-gradient-to-r from-dawn-500 to-dawn-600 hover:from-dawn-400 hover:to-dawn-500 disabled:from-onyx-700 disabled:to-onyx-700 disabled:cursor-not-allowed text-white font-semibold rounded-xl transition-all shadow-lg shadow-dawn-500/20 disabled:shadow-none"
          >
            {isSaving ? '저장 중...' : '서비스 등록하기'}
          </button>

          {savedUrl && (
            <div className="p-4 bg-green-500/10 border border-green-500/30 rounded-xl">
              <p className="text-green-400 text-sm mb-2">✓ 서비스가 등록되었습니다!</p>
              <code className="text-xs text-green-300 bg-green-500/10 px-2 py-1 rounded">{savedUrl}</code>
            </div>
          )}
        </div>

        {/* 미리보기 */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-onyx-100">미리보기</h2>
            <div className="flex gap-2">
              {(['ai.txt', 'llms.txt', 'json-ld'] as const).map((mode) => (
                <button
                  key={mode}
                  onClick={() => setPreviewMode(mode)}
                  className={`px-3 py-1 rounded-lg text-sm transition-colors ${
                    previewMode === mode
                      ? 'bg-dawn-500 text-white'
                      : 'bg-onyx-800 text-onyx-400 hover:text-onyx-200'
                  }`}
                >
                  {mode}
                </button>
              ))}
            </div>
          </div>
          <div className="bg-onyx-900/50 border border-onyx-800 rounded-xl p-4 h-[calc(100vh-300px)] overflow-auto">
            <pre className="text-sm text-onyx-300 font-mono whitespace-pre-wrap">
              {generatePreview()}
            </pre>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => navigator.clipboard.writeText(generatePreview())}
              className="flex-1 py-2 bg-onyx-800 hover:bg-onyx-700 text-onyx-300 rounded-lg transition-colors text-sm"
            >
              📋 복사하기
            </button>
            <button
              onClick={() => {
                const blob = new Blob([generatePreview()], { type: 'text/plain' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = previewMode === 'json-ld' ? 'agent-data.json' : previewMode;
                a.click();
              }}
              className="flex-1 py-2 bg-onyx-800 hover:bg-onyx-700 text-onyx-300 rounded-lg transition-colors text-sm"
            >
              ⬇️ 다운로드
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
