import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'edge';

interface ServiceData {
  name: string;
  nameKo?: string;
  description: string;
  descriptionKo?: string;
  homepage: string;
  apiBase: string;
  endpoints: {
    id: string;
    path: string;
    method: string;
    description: string;
    auth: boolean;
    params: string;
  }[];
  authType: string;
  rateLimit: string;
  contactEmail: string;
}

// 슬러그 생성 (간단한 버전)
function generateSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 30) + '-' + Date.now().toString(36);
}

// ai.txt 형식으로 변환
function generateAiTxt(service: ServiceData, slug: string): string {
  return `# =============================================================================
# ${service.name} AI Interaction Specification (ai.txt)
# Generated by Eoynx Agent Gateway
# Hosted at: https://eoynx.com/s/${slug}
# =============================================================================

[System.Context]
Name: ${service.name}
${service.nameKo ? `Name_KO: ${service.nameKo}` : ''}
Description: ${service.description}
${service.descriptionKo ? `Description_KO: ${service.descriptionKo}` : ''}
Homepage: ${service.homepage}
Contact: ${service.contactEmail}

[API.Base]
URL: ${service.apiBase}

[API.Endpoints]
${service.endpoints.map((ep, i) => `
## ${i + 1}. ${ep.description || 'Endpoint'}
Endpoint: ${ep.method} ${service.apiBase}${ep.path}
Auth: ${ep.auth ? 'Required' : 'Not Required'}
${ep.params ? `Parameters: ${ep.params}` : ''}`).join('\n')}

[Authentication.Policy]
Type: ${service.authType === 'none' ? 'None' : service.authType === 'api_key' ? 'API Key' : service.authType === 'jwt' ? 'JWT Bearer Token' : 'OAuth 2.0'}
${service.authType !== 'none' ? `Header: ${service.authType === 'api_key' ? 'X-API-Key' : 'Authorization: Bearer <token>'}` : ''}

[Rate.Limits]
Default: ${service.rateLimit}

# =============================================================================
# Generated via Eoynx Agent Gateway
# https://eoynx.com
# =============================================================================
`;
}

// JSON-LD 형식으로 변환
function generateJsonLd(service: ServiceData, slug: string): object {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebAPI',
    '@id': `https://eoynx.com/s/${slug}`,
    name: service.name,
    alternateName: service.nameKo || undefined,
    description: service.description,
    url: service.homepage,
    documentation: `${service.homepage}/docs`,
    provider: {
      '@type': 'Organization',
      name: service.name,
      email: service.contactEmail,
    },
    endpointUrl: service.apiBase,
    potentialAction: service.endpoints.map(ep => ({
      '@type': ep.method === 'GET' ? 'ReadAction' : 'Action',
      name: ep.description || ep.path,
      target: {
        '@type': 'EntryPoint',
        urlTemplate: `${service.apiBase}${ep.path}`,
        httpMethod: ep.method,
      },
    })),
    additionalProperty: [
      {
        '@type': 'PropertyValue',
        name: 'authType',
        value: service.authType,
      },
      {
        '@type': 'PropertyValue',
        name: 'rateLimit',
        value: service.rateLimit,
      },
    ],
  };
}

export async function POST(request: NextRequest) {
  try {
    const serviceData: ServiceData = await request.json();
    
    // 필수 필드 검증
    if (!serviceData.name || !serviceData.apiBase || !serviceData.description) {
      return NextResponse.json(
        { error: 'Missing required fields: name, apiBase, description' },
        { status: 400 }
      );
    }
    
    // 슬러그 생성
    const slug = generateSlug(serviceData.name);
    
    // TODO: Supabase에 저장
    // const { data, error } = await supabase
    //   .from('services')
    //   .insert({
    //     slug,
    //     name: serviceData.name,
    //     name_ko: serviceData.nameKo,
    //     description: serviceData.description,
    //     description_ko: serviceData.descriptionKo,
    //     homepage: serviceData.homepage,
    //     api_base: serviceData.apiBase,
    //     endpoints: serviceData.endpoints,
    //     auth_type: serviceData.authType,
    //     rate_limit: serviceData.rateLimit,
    //     contact_email: serviceData.contactEmail,
    //     ai_txt: generateAiTxt(serviceData, slug),
    //     json_ld: generateJsonLd(serviceData, slug),
    //     created_at: new Date().toISOString(),
    //   })
    //   .select()
    //   .single();
    
    // 임시: 메모리에 저장 (프로덕션에서는 DB 사용)
    const result = {
      id: crypto.randomUUID(),
      slug,
      name: serviceData.name,
      createdAt: new Date().toISOString(),
      urls: {
        dashboard: `https://eoynx.com/s/${slug}`,
        aiTxt: `https://eoynx.com/s/${slug}/ai.txt`,
        llmsTxt: `https://eoynx.com/s/${slug}/llms.txt`,
        jsonLd: `https://eoynx.com/s/${slug}/json-ld`,
      },
    };
    
    return NextResponse.json({
      success: true,
      slug,
      service: result,
      preview: {
        aiTxt: generateAiTxt(serviceData, slug),
        jsonLd: generateJsonLd(serviceData, slug),
      },
    }, {
      status: 201,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  } catch (error) {
    console.error('Service creation error:', error);
    return NextResponse.json(
      { error: 'Failed to create service' },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  // 사용자의 서비스 목록 조회
  // TODO: 인증된 사용자의 서비스만 반환
  
  return NextResponse.json({
    services: [],
    message: 'Service listing will be available with authentication',
  });
}
