'use client';

import { useState } from 'react';

interface ParseResult {
  url: string;
  title: string;
  description: string;
  content: string;
  metadata: {
    ogTitle?: string;
    ogDescription?: string;
    ogImage?: string;
    ogType?: string;
    canonical?: string;
    author?: string;
    publishedTime?: string;
    keywords?: string[];
  };
  structuredData: object[];
  links: { text: string; href: string }[];
  headings: { level: number; text: string }[];
  parseTime: number;
  contentLength: number;
  cached: boolean;
}

export default function ProxyPage() {
  const [url, setUrl] = useState('');
  const [result, setResult] = useState<ParseResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [viewMode, setViewMode] = useState<'summary' | 'content' | 'metadata' | 'ai.txt'>('summary');

  const handleParse = async () => {
    if (!url) return;
    
    setLoading(true);
    setError(null);
    setResult(null);
    
    try {
      const response = await fetch('/api/proxy/parse', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url }),
      });
      
      const data = await response.json();
      
      if (!response.ok) {
        throw new Error(data.error || 'Failed to parse URL');
      }
      
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLoading(false);
    }
  };

  const generateAiTxt = (): string => {
    if (!result) return '';
    
    return `# =============================================================================
# ${result.title} - AI Agent Data
# Generated by Eoynx Proxy Parser
# =============================================================================

[Source]
URL: ${result.url}
${result.metadata.canonical ? `Canonical: ${result.metadata.canonical}` : ''}
ParseTime: ${result.parseTime}ms
ContentLength: ${result.contentLength} chars
Cached: ${result.cached ? 'Yes' : 'No'}

[Content]
Title: ${result.title}
Description: ${result.description}

${result.metadata.ogTitle ? `[OpenGraph]
Title: ${result.metadata.ogTitle}
Description: ${result.metadata.ogDescription || ''}
Image: ${result.metadata.ogImage || ''}
Type: ${result.metadata.ogType || ''}` : ''}

${result.metadata.author ? `[Author]
Name: ${result.metadata.author}
${result.metadata.publishedTime ? `Published: ${result.metadata.publishedTime}` : ''}` : ''}

${result.headings.length > 0 ? `[Structure]
${result.headings.map(h => `${'#'.repeat(h.level)} ${h.text}`).join('\n')}` : ''}

[Summary]
${result.content.substring(0, 2000)}${result.content.length > 2000 ? '...' : ''}

${result.links.length > 0 ? `[Related Links]
${result.links.slice(0, 10).map(l => `- ${l.text}: ${l.href}`).join('\n')}` : ''}

# =============================================================================
# Generated via Eoynx Proxy Parser
# https://eoynx.com
# =============================================================================
`;
  };

  return (
    <div className="space-y-6">
      {/* 페이지 제목 */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-onyx-100 flex items-center gap-2">
            <svg className="w-7 h-7 text-dawn-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
            </svg>
            프록시 파서
          </h1>
          <p className="mt-1 text-sm text-onyx-400">
            URL을 입력하면 AI 에이전트가 이해할 수 있는 구조화된 데이터로 변환합니다.
          </p>
        </div>
        <div className="text-xs text-purple-400 bg-purple-500/20 px-3 py-1 rounded-full border border-purple-500/30">
          Pro Feature (Beta)
        </div>
      </div>

      {/* URL 입력 */}
      <div className="bg-onyx-900/50 border border-onyx-800 rounded-xl p-6">
        <div className="flex gap-4">
          <input
            type="url"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder="https://example.com/article"
            className="flex-1 bg-onyx-800 border border-onyx-700 rounded-lg px-4 py-3 text-onyx-100 placeholder-onyx-500 focus:border-dawn-500 focus:outline-none font-mono text-sm"
            onKeyDown={(e) => e.key === 'Enter' && handleParse()}
          />
          <button
            onClick={handleParse}
            disabled={loading || !url}
            className="px-6 py-3 bg-gradient-to-r from-dawn-500 to-dawn-600 hover:from-dawn-400 hover:to-dawn-500 disabled:from-onyx-700 disabled:to-onyx-700 disabled:cursor-not-allowed text-white font-semibold rounded-lg transition-all"
          >
            {loading ? (
              <span className="flex items-center gap-2">
                <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                파싱 중...
              </span>
            ) : '파싱하기'}
          </button>
        </div>
        
        {/* 샘플 URL */}
        <div className="mt-3 flex gap-2 flex-wrap">
          <span className="text-xs text-onyx-500">샘플:</span>
          {[
            'https://news.ycombinator.com',
            'https://github.com',
            'https://eoynx.com',
          ].map((sampleUrl) => (
            <button
              key={sampleUrl}
              onClick={() => setUrl(sampleUrl)}
              className="text-xs text-dawn-400 hover:text-dawn-300 underline"
            >
              {new URL(sampleUrl).hostname}
            </button>
          ))}
        </div>
      </div>

      {/* 에러 */}
      {error && (
        <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-4">
          <p className="text-red-400 text-sm">❌ {error}</p>
        </div>
      )}

      {/* 결과 */}
      {result && (
        <div className="space-y-4">
          {/* 요약 카드 */}
          <div className="grid grid-cols-4 gap-4">
            <div className="bg-onyx-900/50 border border-onyx-800 rounded-lg p-4">
              <div className="text-2xl font-bold text-dawn-400">{result.parseTime}ms</div>
              <div className="text-xs text-onyx-500">파싱 시간</div>
            </div>
            <div className="bg-onyx-900/50 border border-onyx-800 rounded-lg p-4">
              <div className="text-2xl font-bold text-onyx-100">{(result.contentLength / 1000).toFixed(1)}k</div>
              <div className="text-xs text-onyx-500">콘텐츠 길이</div>
            </div>
            <div className="bg-onyx-900/50 border border-onyx-800 rounded-lg p-4">
              <div className="text-2xl font-bold text-onyx-100">{result.headings.length}</div>
              <div className="text-xs text-onyx-500">헤딩 수</div>
            </div>
            <div className="bg-onyx-900/50 border border-onyx-800 rounded-lg p-4">
              <div className="text-2xl font-bold text-onyx-100">{result.structuredData.length}</div>
              <div className="text-xs text-onyx-500">JSON-LD</div>
            </div>
          </div>

          {/* 뷰 모드 탭 */}
          <div className="flex gap-2">
            {(['summary', 'content', 'metadata', 'ai.txt'] as const).map((mode) => (
              <button
                key={mode}
                onClick={() => setViewMode(mode)}
                className={`px-4 py-2 rounded-lg text-sm transition-colors ${
                  viewMode === mode
                    ? 'bg-dawn-500 text-white'
                    : 'bg-onyx-800 text-onyx-400 hover:text-onyx-200'
                }`}
              >
                {mode === 'summary' ? '요약' : mode === 'content' ? '콘텐츠' : mode === 'metadata' ? '메타데이터' : 'ai.txt'}
              </button>
            ))}
          </div>

          {/* 콘텐츠 영역 */}
          <div className="bg-onyx-900/50 border border-onyx-800 rounded-xl p-6">
            {viewMode === 'summary' && (
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-semibold text-onyx-100">{result.title}</h3>
                  <p className="text-sm text-onyx-400 mt-1">{result.description}</p>
                  <a href={result.url} target="_blank" rel="noopener noreferrer" className="text-xs text-dawn-400 hover:underline mt-2 inline-block">
                    {result.url}
                  </a>
                </div>
                
                {result.headings.length > 0 && (
                  <div>
                    <h4 className="text-sm font-semibold text-onyx-300 mb-2">페이지 구조</h4>
                    <div className="space-y-1">
                      {result.headings.slice(0, 10).map((h, i) => (
                        <div key={i} className="text-sm text-onyx-400" style={{ paddingLeft: `${(h.level - 1) * 16}px` }}>
                          <span className="text-onyx-600">{'#'.repeat(h.level)}</span> {h.text}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {result.links.length > 0 && (
                  <div>
                    <h4 className="text-sm font-semibold text-onyx-300 mb-2">관련 링크 ({result.links.length})</h4>
                    <div className="space-y-1">
                      {result.links.slice(0, 5).map((link, i) => (
                        <div key={i} className="text-sm">
                          <a href={link.href} target="_blank" rel="noopener noreferrer" className="text-dawn-400 hover:underline">
                            {link.text || link.href}
                          </a>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}

            {viewMode === 'content' && (
              <div className="max-h-[500px] overflow-auto">
                <pre className="text-sm text-onyx-300 whitespace-pre-wrap font-mono">
                  {result.content}
                </pre>
              </div>
            )}

            {viewMode === 'metadata' && (
              <div className="space-y-4">
                <div>
                  <h4 className="text-sm font-semibold text-onyx-300 mb-2">Open Graph</h4>
                  <div className="bg-onyx-800/50 rounded-lg p-4 space-y-2">
                    {result.metadata.ogTitle && <div className="text-sm"><span className="text-onyx-500">og:title:</span> <span className="text-onyx-200">{result.metadata.ogTitle}</span></div>}
                    {result.metadata.ogDescription && <div className="text-sm"><span className="text-onyx-500">og:description:</span> <span className="text-onyx-200">{result.metadata.ogDescription}</span></div>}
                    {result.metadata.ogImage && (
                      <div className="text-sm">
                        <span className="text-onyx-500">og:image:</span>
                        <img src={result.metadata.ogImage} alt="OG Image" className="mt-2 max-w-xs rounded-lg" />
                      </div>
                    )}
                    {result.metadata.ogType && <div className="text-sm"><span className="text-onyx-500">og:type:</span> <span className="text-onyx-200">{result.metadata.ogType}</span></div>}
                  </div>
                </div>

                {result.structuredData.length > 0 && (
                  <div>
                    <h4 className="text-sm font-semibold text-onyx-300 mb-2">JSON-LD ({result.structuredData.length})</h4>
                    <div className="bg-onyx-800/50 rounded-lg p-4 max-h-[300px] overflow-auto">
                      <pre className="text-xs text-onyx-300 font-mono">
                        {JSON.stringify(result.structuredData, null, 2)}
                      </pre>
                    </div>
                  </div>
                )}
              </div>
            )}

            {viewMode === 'ai.txt' && (
              <div>
                <div className="flex justify-end mb-2">
                  <button
                    onClick={() => navigator.clipboard.writeText(generateAiTxt())}
                    className="text-xs text-dawn-400 hover:text-dawn-300"
                  >
                    📋 복사
                  </button>
                </div>
                <pre className="text-sm text-onyx-300 whitespace-pre-wrap font-mono max-h-[500px] overflow-auto">
                  {generateAiTxt()}
                </pre>
              </div>
            )}
          </div>
        </div>
      )}

      {/* 사용 안내 */}
      {!result && !loading && !error && (
        <div className="bg-onyx-900/30 border border-onyx-800 border-dashed rounded-xl p-8 text-center">
          <div className="text-4xl mb-4">🌐</div>
          <h3 className="text-lg font-semibold text-onyx-200 mb-2">URL을 입력하세요</h3>
          <p className="text-sm text-onyx-500 max-w-md mx-auto">
            웹페이지 URL을 입력하면 광고와 불필요한 요소를 제거하고<br/>
            AI 에이전트가 이해할 수 있는 구조화된 데이터로 변환합니다.
          </p>
          <div className="mt-4 text-xs text-onyx-600">
            지원: HTML 페이지 • 뉴스 기사 • 블로그 • 문서
          </div>
        </div>
      )}
    </div>
  );
}
